{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"error"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/DigiMeSDK\/documentation\/DigiMeSDK\/ServiceError","preciseIdentifier":"s:9DigiMeSDK12ServiceErrorV","text":"ServiceError"},{"kind":"text","text":"?"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/digimesdk\/syncerror\/error"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/DigiMeSDK\/documentation\/DigiMeSDK\/SyncError\/error","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"error"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ServiceError","preciseIdentifier":"s:9DigiMeSDK12ServiceErrorV"},{"kind":"text","text":"?"}],"title":"error","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"s:9DigiMeSDK9SyncErrorV5errorAA07ServiceE0VSgvp","modules":[{"name":"DigiMeSDK"}]},"hierarchy":{"paths":[["doc:\/\/DigiMeSDK\/documentation\/DigiMeSDK","doc:\/\/DigiMeSDK\/documentation\/DigiMeSDK\/SyncError"]]},"references":{"doc://DigiMeSDK/documentation/DigiMeSDK/SyncError":{"role":"symbol","title":"SyncError","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"SyncError"}],"abstract":[{"type":"text","text":"Reason why connecting to source or importing data from source into userâ€™s library failed"}],"identifier":"doc:\/\/DigiMeSDK\/documentation\/DigiMeSDK\/SyncError","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SyncError"}],"url":"\/documentation\/digimesdk\/syncerror"},"doc://DigiMeSDK/documentation/DigiMeSDK":{"role":"collection","title":"DigiMeSDK","abstract":[{"type":"text","text":"Digi.me - The Private Sharing Platform"}],"identifier":"doc:\/\/DigiMeSDK\/documentation\/DigiMeSDK","kind":"symbol","type":"topic","url":"\/documentation\/digimesdk"},"doc://DigiMeSDK/documentation/DigiMeSDK/SyncError/error":{"role":"symbol","title":"error","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"error"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ServiceError","preciseIdentifier":"s:9DigiMeSDK12ServiceErrorV"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/DigiMeSDK\/documentation\/DigiMeSDK\/SyncError\/error","kind":"symbol","type":"topic","url":"\/documentation\/digimesdk\/syncerror\/error"},"doc://DigiMeSDK/documentation/DigiMeSDK/ServiceError":{"role":"symbol","title":"ServiceError","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"ServiceError"}],"abstract":[],"identifier":"doc:\/\/DigiMeSDK\/documentation\/DigiMeSDK\/ServiceError","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ServiceError"}],"url":"\/documentation\/digimesdk\/serviceerror"}}}